module.exports = {
    'he-IL': {
        'grid': {
            'Add': 'הוסף',
            'Edit': 'ערוך',
            'Delete': 'מחק',
            'Update': 'שמור',
            'Cancel': 'בטל',
            'ConfirmDelete': '?האם את/ה בטוח/ה שברצונך למחוק רשומה זו',
            'OKButton': 'אישור',
            'CancelButton': 'ביטול',
            'FilterButton': 'סנן',
            'ClearButton': 'נקה',
            'Excelexport': 'Excel',
            'ClearFilter': 'נקה פילטר',
            'NumberFilter': 'פילטר מספרים',
            'TextFilter': 'פילטר טקסט',
            'DateFilter': 'פילטר תאריך',
            'Equal': 'שווה',
            'NotEqual': 'אינו שווה',
            'LessThan': 'פחות מ',
            'LessThanOrEqual': 'פחות או שווה ל',
            'GreaterThan': 'גדול מ',
            'GreaterThanOrEqual': 'גדול או שווה ל',
            'ChooseDate': 'בחר תאריך',
            'EnterValue': 'הכנס ערך',
            'StartsWith': 'מתחיל ב',
            'EndsWith': 'נגמר ב',
            'Contains': 'מכיל',
            'CustomFilter': 'מותאם אישית',
            'CustomFilterPlaceHolder': 'הכנס ערך',
            'CustomFilterDatePlaceHolder': 'בחר תאריך',
            'FirstPage': 'עמוד ראשון',
            'LastPage': 'עמוד אחרון',
            'PreviousPage': 'עמוד קודם',
            'NextPage': 'עמוד הבא',
            'currentPageInfo': '{0} מתוך {1} עמודים',
            'totalItemsInfo': '({0} פריטים)',
            'Item': 'פריט',
            'Items': 'פריטים',
            'pagerDropDown': 'פריטים לעמוד',
            'pagerAllDropDown': 'פריטים',
            'All': 'הכל',

        }
    }
};